default_platform(:ios)

platform :ios do
  desc "Release new build to TestFlight"
  lane :alpha do
    increment_build_number(build_number: latest_testflight_build_number + 1,xcodeproj: "react_native_starter_kit.xcodeproj")
    gym(scheme:"react_native_starter_kit",export_method: "app-store",clean: true)
    pilot(skip_waiting_for_build_processing:true)	
    clean_build_artifacts
    commit_version_bump(
      message:"iOS: Alpha release new build #{lane_context[SharedValues::BUILD_NUMBER]} [ci skip]",	
      xcodeproj: "react_native_starter_kit.xcodeproj",	
      force:true	
    )
  end
end
